# Generated by Django 4.0.6 on 2022-11-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['date_started'],
            },
        ),
    ]
