# Generated by Django 4.0.6 on 2022-11-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date_applied', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('submission_source', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Glassdoor', 'Glassdoor'), ('Monster', 'Monster'), ('Indeed', 'Indeed'), ('Company Website', 'Company Website'), ('Other', 'Other')], max_length=255)),
                ('stage', models.CharField(choices=[('Recruiter Phone Screen', 'Recruiter Phone Screen'), ('Behavioral Interview', 'Behavioral Interview'), ('First Technical Interview', 'First Technical Interview'), ('Second Technical Interview', 'Second Technical Interview'), ('Third Technical Interview', 'Third Technical Interview'), ('Other', 'Other')], max_length=255)),
                ('final_decision', models.CharField(choices=[('No Offer', 'No Offer'), ('Offer Accepted', 'Offer Accepted'), ('Offer Rejected', 'Offer Rejected'), ('Company Ghosted Me', 'Company Ghosted Me'), ('I Ghosted Company', 'I Ghosted Company'), ('Counter Offer Pending', 'Counter Offer Pending')], max_length=255)),
                ('contact_info', models.TextField()),
                ('salary_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_job_apps', to='jobsite.jobsearch')),
            ],
            options={
                'ordering': ['job_search__date_started'],
            },
        ),
    ]
